-- Script generated by SimpleSpy - credits to exx#9394
task.spawn(function()
    while true do
        local args = {
            [1] = {
                [1] = {
                    ["animationIndex"] = 0,
                    ["sentAt"] = 1732317104.487091
                },
                [2] = "\151"
            }
        }
        game:GetService("ReplicatedStorage").dataRemoteEvent:FireServer(unpack(args))
        index += 1

        if index >= 3 then
            index = 1
        end

        task.wait()
    end
end)
