loadstring(game:HttpGet("https://raw.githubusercontent.com/exxtremestuffs/SimpleSpySource/refs/heads/master/SimpleSpy.lua"))()



-- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").remotes.changeStartValue:FireServer()
