loadstring(game:HttpGet("https://raw.githubusercontent.com/exxtremestuffs/SimpleSpySource/refs/heads/master/SimpleSpy.lua"))()



-- Script generated by SimpleSpy - credits to exx#9394

game:GetService("ReplicatedStorage").remotes.changeStartValue:FireServer()


-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = CFrame.new(-98.05381774902344, -734.9266357421875, 1211.1822509765625) * CFrame.Angles(0, -1.2751245498657227, -0)
}

game:GetService("Players").LocalPlayer.Character:FindFirstChild("Crab Cage").Deploy:FireServer(unpack(args))

-- Script generated by SimpleSpy - credits to exx#9394

workspace.world.npcs.Appraiser.appraiser.appraise:InvokeServer()


-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        ["y"] = -696.315,
        ["x"] = 95.607,
        ["z"] = -967.854
    }
}

game:GetService("ReplicatedStorage").events.open_treasure:FireServer(unpack(args))
